production:
  clients:
    default:
      database: bible
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false

development:
  clients:
    default:
      database: bible
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    
test:
  clients:
    default:
      database: bible
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
